---
# tasks file for apache-role
- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest
  when: (ansible_distribution == "CentOS")

- name: Install the package "httpd"
  apt:
    name: apache2
    state: latest
    force_apt_get: true
  when: (ansible_distribution == "Ubuntu")

- name: Make sure a service is running
  systemd:
    state: started
    name: apache2
